export const itSkills = [
  { title: "JavaScript" },
  { title: "ReactJS" },
  { title: "Node.js" },
  { title: "Python" },
  { title: "Java" },
  { title: "SQL" },
  { title: "Git" },
  { title: "Docker" },
  { title: "AWS" },
  { title: "Angular" },
  { title: "HTML/CSS" },
  { title: "TypeScript" },
  { title: "C++" },
  { title: "Ruby on Rails" },
  { title: "RESTful API Design" },
  { title: "Redux" },
  { title: "GraphQL" },
  { title: "Vue.js" },
  { title: "MongoDB" },
  { title: "CI/CD" },
  { title: "Kubernetes" },
  { title: "Cloud Computing" },
  { title: "Cybersecurity" },
  { title: "Machine Learning" },
  { title: "Data Science" },
  { title: "UI/UX Design" },
  { title: "Network Administration" },
  { title: "DevOps" },
  { title: "Agile Methodologies" },
  { title: "Software Testing" },
  { title: "Microservices" },
  { title: "Big Data" },
  { title: "Blockchain" },
  { title: "IoT" },
  { title: "Mobile App Development" },
  { title: "Web Development" },
  { title: "Backend Development" },
  { title: "Frontend Development" },
  { title: "Full-stack Development" },
  { title: "Database Management" },
  { title: "Linux/Unix Administration" },
  { title: "Shell Scripting" },
  { title: "Version Control" },
  { title: "Containerization" },
  { title: "Infrastructure as Code" },
  { title: "Cloud Services" },
  { title: "System Architecture" },
  { title: "Software Design Patterns" },
  { title: "API Integration" },
  { title: "Web Security" },
  { title: "Performance Optimization" },
  { title: "Technical Documentation" },
  { title: "Continuous Integration" },
  { title: "Continuous Deployment" },
];
